openebs/ci-e2e-dashboard-backend

.gitignore, server.js
- change pooling time form 8000ms to 20000ms
- Add git ignore file
=> Modify server.js file for api call time change

README.md, server.js
- Pass gitlab-api-token as a environment variable
=> Modify server.js file for pass gitlab-token

server.js
- Add packet jobs inside packet pipeline from gitlab
=> Populate jobs for packet pipelines

server.js
- Fetch pipelines and jobs details form gitlab using gitlab api
=> Add azure pipeline and job for dashboard api

Dockerfile, launch.sh
=> Modify Dockerfile for passing token as variable

server.js
- Add function for handle edge case when no any data available in
gitlab jobs or pipeline triger failed in gitlab
=> Edge case handle when no job data available

README.md, launch.sh, main.js, package.json, src/aws.js, src/azure.js, src/commit.js, src/gcp.js, src/time-calculate.js
- Add a new folder `src` which contains all platform specific functions
- rename `server.js` file to `main.js` file
- Modify launch.sh for staring `main.js` file
Issue: #15 
=> Refactoring ci-dashboard-backend code

main.js, src/kibana_log.js
- Dynamic kibana log url generated according to the pipeline status
> if pipeline status is passed or failed then it pass the log url with time interval a/c to start job time and end job time of gitlab
> Otherwise it passed the log url time is `3-hour from now`
=> Add kibana log url with dynamic time interval

src/aws.js, src/azure.js, src/gcp.js
- This will fetch the gitlab pipelines for master branch using `ref=master` 
=> Fetch gitlab pipelines from master branch

main.js, src/gke.js
-  Add file `gke.js` for for get the pipeline status of GKE using gitlab
Api
- Modify `main.js` for render the JSON format and push data to route path
=> Add support for get pipielines details of GKE

main.js, src/aks.js, src/build.js, src/eks.js, src/gcp.js, src/gke.js, src/packet.js, src/time-calculate.js
- Fetch AKS & EKS pipelines details from gitlab
- Fetch build pipeline details from gitlab
=> Add AKS and EKS pielines data

main.js, package.json, src/build.js
=> Modify build stage pipeline data

src/eks.js
=> update eks file fetch data

main.js, src/build.js, src/time-calculate.js
=> Change project id of maya and jiva

main.js, src/kibana_log.js
fix kibana log link generation and add dummy pipeline data if build is running
=> Fix kibana log link generation

main.js, src/time-calculate.js
=> Modify dummy json value and fix commit update time

main.js
- This will add dummy json data with status pending only when build is running or pipelines not created, after that this data will removed automatically
=> Modify status of dummy json and their attachment

src/aks.js, src/aws.js, src/build.js, src/commit.js, src/eks.js, src/gcp.js, src/gke.js, src/packet.js
- Update all platform project id with updated project details
=> [Modify]: Update project_id of platform and projects

src/aks.js, src/aws.js, src/build.js, src/commit.js, src/eks.js, src/gcp.js, src/gke.js, src/packet.js
- Update project_id of platform build repo
=> [update]: Update project_id of platform build repo

main.js
=> [fix] Add dummy pipeline json when build is running

main.js
=> [fix] Add all platform pipeline json data

main.js, src/build.js
This PR will fix the build pipeline data fluctuation
=> fix build pipeline data fluctuation

main.js, src/build.js
- zfs branch changed as ''' zfs-0.7-release ''' .
- istgt branch changes to ''' replication '''
=> Fix(typo) : Updated reference branch for cStor & istgt

src/aks.js, src/build.js, src/eks.js, src/gke.js
Signed-off-by: inyee786 <intakhab.ali@mayadata.io>
=> Update gitlab domain and projectID
